-- VULNERABLE: D-11 시스템 테이블 접근 제한 미흡 - RLS 비활성화
-- Supabase RLS(Row Level Security)를 활성화하여 정책을 적용해야 합니다.
-- 현재는 RLS가 비활성화되어 있어, 인증된 사용자가 모든 데이터에 접근할 수 있습니다.

-- VULNERABLE: D-18 Role Public 설정 - public 스키마에 대한 불필요한 권한 부여
-- 기본적으로 public 스키마에 대한 모든 권한을 허용합니다. 실제 환경에서는 최소 권한 원칙을 적용해야 합니다.
GRANT ALL PRIVILEGES ON SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO postgres;

-- Enum for UserRole
CREATE TYPE user_role_enum AS ENUM (
    'user',
    'admin',
    'super_admin'
);

-- Enum for UserStatus
CREATE TYPE user_status_enum AS ENUM (
    'pending',
    'approved',
    'rejected'
);

-- Enum for ApplicationStatus
CREATE TYPE application_status_enum AS ENUM (
    'pending',
    'approved',
    'rejected'
);

-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(50) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    role user_role_enum DEFAULT 'user'::user_role_enum,
    status user_status_enum DEFAULT 'pending'::user_status_enum,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Schedules Table
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    start_time_str VARCHAR(5) NOT NULL,
    end_time_str VARCHAR(5) NOT NULL,
    work_date TIMESTAMPTZ NOT NULL,
    capacity INTEGER DEFAULT 1,
    current_applicants INTEGER DEFAULT 0
);

-- Applications Table
CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    schedule_id BIGINT REFERENCES schedules(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    status application_status_enum DEFAULT 'pending'::application_status_enum
);

-- Notices Table
CREATE TABLE notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(4000) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    view_count INTEGER DEFAULT 0,
    is_pinned BOOLEAN DEFAULT FALSE
);

-- VULNERABLE: D-01 기본 계정 보안 미흡 - 하드코딩된 초기 관리자 계정
-- 실제 환경에서는 초기 관리자 계정을 안전하게 생성하고 관리해야 합니다.
-- D-04 관리자 권한 제한 미흡 - 최고 관리자 계정의 비밀번호가 코드에 노출
INSERT INTO users (phone_number, username, hashed_password, role, status) VALUES
(
    '01099074438',
    'supernova',
    -- 'kspo88!'을 bcrypt로 해싱한 값 (실제로는 안전하게 생성해야 함)
    '$2a$10$Q.12345678901234567890123456789012345678901234567890',
    'super_admin',
    'approved'
),
(
    '01000000002',
    'olympic88',
    -- 'banquet88!'을 bcrypt로 해싱한 값 (실제로는 안전하게 생성해야 함)
    '$2a$10$R.12345678901234567890123456789012345678901234567890',
    'admin',
    'approved'
);

-- RLS 정책 비활성화 (의도적인 취약점 주입)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;

-- VULNERABLE: D-11 시스템 테이블 접근 제한 미흡 - RLS 정책을 추가하지 않아 모든 사용자가 모든 데이터에 접근 가능
-- 실제 환경에서는 각 테이블에 대한 RLS 정책을 세밀하게 정의해야 합니다.
-- 예를 들어, 사용자 본인의 데이터만 조회/수정 가능하도록 설정해야 합니다.
-- CREATE POLICY "Users can view their own data" ON users FOR SELECT USING (auth.uid() = id);
-- CREATE POLICY "Users can update their own data" ON users FOR UPDATE USING (auth.uid() = id);
